### ISSUE TITLE
cloud notebook sample breaks

### ISSUE THREAD

**Issue by idomic** [ploomber/projects#85]
[This notebook](https://raw.githubusercontent.com/ploomber/projects/master/guides/cloud-notebooks-user-guide/notebooks/input-data.ipynb?utm_source=ploomber&utm_medium=blog&utm_campaign=cloud-notebooks-gui) breaks on PythonCallable deprecated ValueError.

**Comment by edublancas** [comment]
do you have the full traceback?

**Comment by NiclaAuletta** [comment]
Hello everyone. Here is the full traceback:
Traceback (most recent call last): File "/opt/conda/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/opt/conda/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "/opt/conda/lib/python3.10/site-packages/ploomber/__init__.py", line 2, in <module> from ploomber.dag.dag import DAG File "/opt/conda/lib/python3.10/site-packages/ploomber/dag/dag.py", line 94, in <module> from ploomber.dag.dagclients import DAGClients File "/opt/conda/lib/python3.10/site-packages/ploomber/dag/dagclients.py", line 4, in <module> from ploomber.tasks.abc import Task File "/opt/conda/lib/python3.10/site-packages/ploomber/tasks/__init__.py", line 1, in <module> from ploomber.tasks.tasks import (PythonCallable, ShellScript, DownloadFromURL, File "/opt/conda/lib/python3.10/site-packages/ploomber/tasks/tasks.py", line 60, in <module> class PythonCallable(Task): File "/opt/conda/lib/python3.10/site-packages/ploomber/tasks/tasks.py", line 270, in PythonCallable @deprecated.method(deprecated_in='0.21', removed_in='0.22') TypeError: method() got an unexpected keyword argument 'removed_in'
